name: Testing
# means everytime someone push run this code
on: push

# every workflow consist of jobs
jobs:
  # name of the job
  test_project:
    # selecting virtual mechine
    run-on: ubuntu-latest
    steps:
    # check out the code
    - uses: action/checkout@v2
    - name: Run Django unit tests
      run: |
        pip install --user django
        python3 manage.py test